#!/usr/bin/env python3
"""Copy tag refs to new tags"""

import os.path
import sys

from git import Repo

arg0 = os.path.basename(sys.argv[0])


def die(msg):
    sys.exit(f'{arg0}: {msg}')


def main(args: list[str]):
    repo = Repo.init()
    for arg in args[1:]:
        if len(arg.split('=')) != 2:
            die('<dst_tag>=<src_tag> [...]')
        dst, src = arg.split('=')
        try:
            ref = repo.commit(src)
        except Exception as e:
            die(e)
        repo.create_tag(dst, ref=ref, message=f'Tagged by {arg0}', force=True)


if __name__ == '__main__':
    main(sys.argv)
