#!/usr/bin/env python3
"""Load tag refs from JSON"""

import json
import sys

from git import Repo


def main(args: list[str]):
    repo = Repo.init()
    load = json.load(sys.stdin)
    for tag, ref in load.items():
        try:
            _ = repo.commit(ref)
        except:
            sys.exit(f'Ref not found: {ref} (tag: {tag})')
        repo.create_tag(tag, ref=ref, message=f'Tagged by {args[0]}', force=True)


if __name__ == '__main__':
    main(sys.argv)
