#!/usr/bin/env python3
"""Load tag refs from JSON"""

import json
import os.path
import sys

from git import Repo


def die(e: Exception):
    sys.exit(f'{os.path.basename(sys.argv[0])}: {e.__traceback__.tb_lineno}: {e}')


def main(args: list[str]):
    repo = Repo.init()
    load = json.load(sys.stdin)
    for tag, ref in load.items():
        try:
            _ = repo.commit(ref)
        except Exception as e:
            die(e)
        repo.create_tag(tag, ref=ref, message=f'Tagged by {args[0]}', force=True)


if __name__ == '__main__':
    main(sys.argv)
