#!/usr/bin/env python3

from git import Repo

repo = Repo.init()
head = repo.head
tags = repo.tags
prev = tags['previous'] if 'previous' in tags else head
curr = tags['current'] if 'current' in tags else head

print('head', head.commit)
print('previous', prev.commit)
print('current', curr.commit)
