#!/usr/bin/env python3
"""Save tag refs to JSON"""

import json
import os.path
import sys

from git import Repo


def die(e: Exception):
    sys.exit(f'{os.path.basename(sys.argv[0])}: {e.__traceback__.tb_lineno}: {e}')


def main(args: list[str]):
    repo = Repo.init()
    save = {}
    for tag in args[1:]:
        try:
            ref = repo.tag(tag).commit.hexsha
        except Exception as e:
            die(e)
        save[tag] = ref
    print(json.dumps(save))


if __name__ == '__main__':
    main(sys.argv)
