#!/usr/bin/env python3
"""Save tag refs to JSON"""

import json
import sys

from git import Repo


def main(args: list[str]):
    repo = Repo.init()
    head = repo.head
    tags = repo.tags
    save = {tag: (tags[tag] if tag in tags else head).commit.hexsha for tag in args[1:]}
    print(json.dumps(save))


if __name__ == '__main__':
    main(sys.argv)
